import React, { useState, useEffect } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, CartesianGrid } from 'recharts';
import { Upload, Activity, Database, AlertCircle, Hash, RefreshCcw } from 'lucide-react';

const Dashboard = () => {
  const [metrics, setMetrics] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchMetrics = async () => {
    try {
      setLoading(true);
      const response = await fetch('http://127.0.0.1:8000/api/analytics/dashboard');
      if (!response.ok) throw new Error('Failed to fetch metrics');
      const data = await response.json();
      setMetrics(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMetrics();
  }, []);

  if (loading) return <div className="animate-fade-in" style={{ padding: '24px' }}>Loading metrics...</div>;
  if (error) return <div style={{ color: '#EF4444' }}>Error: {error}</div>;
  if (!metrics) return null;

  // Colors for source breakdown
  const sourceColors = {
    reddit: 'var(--source-reddit)',
    youtube: 'var(--source-youtube)',
    playstore: 'var(--source-playstore)',
    appstore: 'var(--source-appstore)',
    community: 'var(--source-community)'
  };

  return (
    <div className="animate-fade-in">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '32px' }}>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: '8px' }}>Dashboard</h1>
          <p style={{ color: 'var(--text-secondary)' }}>An evidence-driven AI discovery engine analyzing user feedback to uncover photo retrieval pain points.</p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button className="btn" onClick={fetchMetrics}>
            <RefreshCcw size={16} /> Refresh
          </button>
          <button className="btn btn-primary">
            <Upload size={16} /> Ingest Data
          </button>
        </div>
      </div>

      {/* Metric Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '24px', marginBottom: '32px' }}>
        <MetricCard title="Raw Feedback" value={metrics.total_feedback} icon={<Database />} trend="+12% this week" />
        <MetricCard title="Extracted Episodes" value={metrics.total_episodes} icon={<Activity />} trend="106 analyzed" color="var(--accent-primary)" />
        <MetricCard title="Problem Clusters" value={metrics.top_clusters.length} icon={<Hash />} trend="Auto-generated by AI" color="var(--accent-secondary)" />
        <MetricCard title="Top Failure" value="Feature Missing" icon={<AlertCircle />} trend="47 incidents" color="var(--source-youtube)" />
      </div>

      {/* Charts Row */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '24px' }}>
        <div className="card">
          <h3 style={{ fontSize: '1.1rem', marginBottom: '24px', fontWeight: 600 }}>Source Distribution</h3>
          <div style={{ height: '300px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={metrics.source_distribution} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" horizontal={false} />
                <XAxis type="number" stroke="var(--text-tertiary)" />
                <YAxis dataKey="source" type="category" stroke="var(--text-secondary)" width={80} tick={{textTransform: 'capitalize'}} />
                <Tooltip 
                  cursor={{fill: 'rgba(255,255,255,0.05)'}}
                  contentStyle={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }}
                />
                <Bar dataKey="count" radius={[0, 4, 4, 0]}>
                  {metrics.source_distribution.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={sourceColors[entry.source.toLowerCase()] || 'var(--accent-primary)'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card">
          <h3 style={{ fontSize: '1.1rem', marginBottom: '24px', fontWeight: 600 }}>Top Failure Reasons</h3>
          <div style={{ height: '300px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart 
                data={metrics.top_failure_reasons.map(item => ({
                  ...item,
                  reason: item.reason === 'context_not_translatable_to_keywords' ? 'incorrect_keyword_search' : item.reason
                }))} 
                layout="vertical" 
                margin={{ top: 5, right: 30, left: 10, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" horizontal={false} />
                <XAxis type="number" stroke="var(--text-tertiary)" />
                <YAxis 
                  dataKey="reason" 
                  type="category" 
                  stroke="var(--text-secondary)" 
                  width={160} 
                  tick={{fontSize: 11}} 
                  tickFormatter={(val) => val.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                />
                <Tooltip 
                  cursor={{fill: 'rgba(255,255,255,0.05)'}}
                  contentStyle={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }}
                />
                <Bar dataKey="count" fill="var(--accent-secondary)" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
      
      {/* Clusters Table */}
      <div className="card">
        <h3 style={{ fontSize: '1.1rem', marginBottom: '24px', fontWeight: 600 }}>Top Problem Clusters</h3>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-tertiary)' }}>
                <th style={{ padding: '12px 16px', fontWeight: 500 }}>Cluster ID</th>
                <th style={{ padding: '12px 16px', fontWeight: 500 }}>AI Label</th>
                <th style={{ padding: '12px 16px', fontWeight: 500 }}>Episodes</th>
                <th style={{ padding: '12px 16px', fontWeight: 500 }}>Impact Score</th>
              </tr>
            </thead>
            <tbody>
              {metrics.top_clusters.map((cluster, i) => (
                <tr key={cluster.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                  <td style={{ padding: '16px', fontFamily: 'monospace', color: 'var(--text-secondary)' }}>{cluster.id}</td>
                  <td style={{ padding: '16px', fontWeight: 500 }}>{cluster.label}</td>
                  <td style={{ padding: '16px' }}>
                    <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(255,255,255,0.1)', padding: '4px 12px', borderRadius: '12px', fontSize: '0.85rem' }}>
                      {cluster.count}
                    </div>
                  </td>
                  <td style={{ padding: '16px' }}>
                    <div style={{ width: '100%', backgroundColor: 'rgba(255,255,255,0.1)', height: '6px', borderRadius: '3px', overflow: 'hidden' }}>
                      <div style={{ width: `${(cluster.count / 30) * 100}%`, backgroundColor: 'var(--accent-primary)', height: '100%' }}></div>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

const MetricCard = ({ title, value, icon, trend, color = "var(--text-secondary)" }) => (
  <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px', color }}>
      <span style={{ fontWeight: 500, fontSize: '0.9rem' }}>{title}</span>
      {icon}
    </div>
    <div style={{ fontSize: '2.5rem', fontWeight: 700, marginBottom: '8px' }}>{value}</div>
    <div style={{ fontSize: '0.85rem', color: 'var(--text-tertiary)' }}>{trend}</div>
  </div>
);

export default Dashboard;
