"""
ProblemCluster ORM model.

Represents a thematic grouping of RetrievalEpisodes identified
by the UMAP + HDBSCAN clustering pipeline and labelled by the LLM.

Schema matches architecture §3.4.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column, String, Text, Integer, DateTime, JSON
)

from backend.db.database import Base


class ProblemCluster(Base):
    """
    A thematic problem area grouping related retrieval episodes.

    Each cluster is generated by the clustering pipeline and labelled
    by the LLM with a human-readable name and summary.
    """

    __tablename__ = "problem_clusters"

    # ── Primary Key ───────────────────────────────────────────
    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        doc="Unique identifier (UUID)"
    )

    # ── Cluster Identity ──────────────────────────────────────
    label = Column(
        String(255),
        nullable=False,
        doc="Human-readable cluster label (e.g., 'Event/Trip-Based Retrieval')"
    )
    summary = Column(
        Text,
        nullable=True,
        doc="LLM-generated summary describing this problem area"
    )
    episode_count = Column(
        Integer,
        nullable=False,
        default=0,
        doc="Number of episodes assigned to this cluster"
    )

    # ── Aggregate Pattern Data ────────────────────────────────
    common_remembered_clues = Column(
        JSON,
        nullable=True,
        default=list,
        doc="Most frequently remembered clue types in this cluster"
    )
    common_forgotten_info = Column(
        JSON,
        nullable=True,
        default=list,
        doc="Most frequently forgotten info types in this cluster"
    )
    common_retrieval_methods = Column(
        JSON,
        nullable=True,
        default=list,
        doc="Most common retrieval methods tried by users in this cluster"
    )
    common_failure_reasons = Column(
        JSON,
        nullable=True,
        default=list,
        doc="Most common failure reasons in this cluster"
    )

    # ── Representative Evidence ───────────────────────────────
    representative_evidence = Column(
        JSON,
        nullable=True,
        default=list,
        doc="List of representative episode IDs for this cluster"
    )
    source_distribution = Column(
        JSON,
        nullable=True,
        default=dict,
        doc="Distribution of sources: {'reddit': 22, 'youtube': 10, ...}"
    )

    # ── Timestamps ────────────────────────────────────────────
    created_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        doc="When this cluster was first created"
    )
    updated_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        doc="When this cluster was last updated"
    )

    def __repr__(self) -> str:
        return (
            f"<ProblemCluster(id={self.id[:8]}..., "
            f"label='{self.label}', "
            f"episodes={self.episode_count})>"
        )
